class BrandScopedCategoryItemConfig {
  final String brandId;
  final List<String> brandAliases;
  final String brandLabelAr;
  final String labelAr;
  final String categorySlug;
  final String? sectionTitleAr;
  final int orderIndex;

  const BrandScopedCategoryItemConfig({
    required this.brandId,
    required this.brandAliases,
    required this.brandLabelAr,
    required this.labelAr,
    required this.categorySlug,
    required this.orderIndex,
    this.sectionTitleAr,
  });

  String get stableKey => '${brandId}_${orderIndex}_$categorySlug';
}

class BrandScopedCategoryConfigSection {
  final String? titleAr;
  final List<BrandScopedCategoryItemConfig> items;

  const BrandScopedCategoryConfigSection({
    required this.titleAr,
    required this.items,
  });
}

class BrandScopedCategoryMenuConfig {
  final String brandId;
  final String brandLabelAr;
  final List<String> brandAliases;
  final List<BrandScopedCategoryConfigSection> sections;

  const BrandScopedCategoryMenuConfig({
    required this.brandId,
    required this.brandLabelAr,
    required this.brandAliases,
    required this.sections,
  });

  List<BrandScopedCategoryItemConfig> get items =>
      sections.expand((section) => section.items).toList(growable: false);
}

abstract class BrandScopedCategoryMenuSource {
  const BrandScopedCategoryMenuSource();

  List<BrandScopedCategoryItemConfig> get items;
}

const List<String> _deliBrandAliases = <String>['deli', 'ديلي'];
const List<String> _zeroBrandAliases = <String>[
  'zero',
  'zero-miss',
  'zero miss',
  'زيرو',
  'زيرو ميس',
];
const List<String> _zidnyBrandAliases = <String>[
  'zidny',
  'زدني',
  'زيدني',
  'alameer-alsagheer',
];

class LocalBrandScopedCategoryMenuSource extends BrandScopedCategoryMenuSource {
  const LocalBrandScopedCategoryMenuSource();

  static const List<BrandScopedCategoryItemConfig> _items =
      <BrandScopedCategoryItemConfig>[
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'أقلام حبر جاف',
          categorySlug: 'ballpoint-pens',
          sectionTitleAr: 'تصنيفات ديلي الأصلية',
          orderIndex: 1,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'أقلام حبر جل',
          categorySlug: 'gel-ink-pens',
          sectionTitleAr: 'تصنيفات ديلي الأصلية',
          orderIndex: 2,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'أقلام حبر سائل',
          categorySlug: 'liquid-ink-pens',
          sectionTitleAr: 'تصنيفات ديلي الأصلية',
          orderIndex: 3,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'أقلام هدية',
          categorySlug: 'deli-gift-pens',
          sectionTitleAr: 'تصنيفات ديلي الأصلية',
          orderIndex: 4,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'أقلام حبر قاعدة سطح المكتب',
          categorySlug: 'deli-desk-base-pens',
          sectionTitleAr: 'تصنيفات ديلي الأصلية',
          orderIndex: 5,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'أقلام سبورة',
          categorySlug: 'whiteboard-markers',
          sectionTitleAr: 'تصنيفات ديلي الأصلية',
          orderIndex: 6,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'أقلام تخطيط',
          categorySlug: 'highlighters',
          sectionTitleAr: 'تصنيفات ديلي الأصلية',
          orderIndex: 7,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'أقلام تأشير',
          categorySlug: 'highlight-markers',
          sectionTitleAr: 'تصنيفات ديلي الأصلية',
          orderIndex: 8,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'أقلام رصاص',
          categorySlug: 'pencils',
          sectionTitleAr: 'تصنيفات ديلي الأصلية',
          orderIndex: 9,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'تلوين مدرسي',
          categorySlug: 'colored-pencils',
          sectionTitleAr: 'تصنيفات ديلي الأصلية',
          orderIndex: 10,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'مماحي',
          categorySlug: 'erasers',
          sectionTitleAr: 'تصنيفات ديلي الأصلية',
          orderIndex: 11,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'ممبرايات',
          categorySlug: 'sharpeners',
          sectionTitleAr: 'تصنيفات ديلي الأصلية',
          orderIndex: 12,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'مصححات',
          categorySlug: 'correction-pens',
          sectionTitleAr: 'تصنيفات ديلي الأصلية',
          orderIndex: 13,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'مقصات ومشارط',
          categorySlug: 'scissors-scalpels-blades',
          sectionTitleAr: 'التصنيفات الجديدة المضافة',
          orderIndex: 14,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'مساطر',
          categorySlug: 'deli-rulers',
          sectionTitleAr: 'التصنيفات الجديدة المضافة',
          orderIndex: 15,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'علب هندسية وأدواتها',
          categorySlug: 'geometryboxes-drawinginstruments',
          sectionTitleAr: 'التصنيفات الجديدة المضافة',
          orderIndex: 16,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'أدوات مدرسية',
          categorySlug: 'deli-school-supplies',
          sectionTitleAr: 'التصنيفات الجديدة المضافة',
          orderIndex: 17,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'دفاتر',
          categorySlug: 'notebooks',
          sectionTitleAr: 'التصنيفات الجديدة المضافة',
          orderIndex: 18,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'ورق ملاحظات',
          categorySlug: 'note-paper',
          sectionTitleAr: 'التصنيفات الجديدة المضافة',
          orderIndex: 19,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'لواصق',
          categorySlug: 'adhesives',
          sectionTitleAr: 'التصنيفات الجديدة المضافة',
          orderIndex: 20,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'آلات حاسبة',
          categorySlug: 'calculators',
          sectionTitleAr: 'التصنيفات الجديدة المضافة',
          orderIndex: 21,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'آلات تجليد حراري ومستلزماتها',
          categorySlug: 'thermal-laminating-machinesd-deli',
          sectionTitleAr: 'التصنيفات المضافة حديثاً بعد آلات حاسبة',
          orderIndex: 22,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'خرازات',
          categorySlug: 'hole-punchers-staplers-binder-clips',
          sectionTitleAr: 'التصنيفات المضافة حديثاً بعد آلات حاسبة',
          orderIndex: 23,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'طابعات',
          categorySlug: 'electronics-printers-and-batteries',
          sectionTitleAr: 'التصنيفات المضافة حديثاً بعد آلات حاسبة',
          orderIndex: 24,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'قطاعات',
          categorySlug: 'scissors-scalpels-blades',
          sectionTitleAr: 'التصنيفات المضافة حديثاً بعد آلات حاسبة',
          orderIndex: 25,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'ثقابات',
          categorySlug: 'hole-punchers-staplers-binder-clips',
          sectionTitleAr: 'التصنيفات المضافة حديثاً بعد آلات حاسبة',
          orderIndex: 26,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'دبابيس وملاقط ومشابك ورق',
          categorySlug: 'hole-punchers-staplers-binder-clips',
          sectionTitleAr: 'التصنيفات المضافة حديثاً بعد آلات حاسبة',
          orderIndex: 27,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'مصنفات',
          categorySlug: 'folders-and-paper-trays',
          sectionTitleAr: 'التصنيفات المضافة حديثاً بعد آلات حاسبة',
          orderIndex: 28,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'مستلزمات مكتبية',
          categorySlug: 'office-accessories',
          sectionTitleAr: 'التصنيفات المضافة حديثاً بعد آلات حاسبة',
          orderIndex: 29,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'فنون',
          categorySlug: 'drawing-tools',
          sectionTitleAr: 'التصنيفات المضافة حديثاً بعد آلات حاسبة',
          orderIndex: 30,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'تجهيزات مكتب',
          categorySlug: 'office-accessories',
          sectionTitleAr: 'التصنيفات المضافة حديثاً بعد آلات حاسبة',
          orderIndex: 31,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'تلافات',
          categorySlug: 'paper-clips',
          sectionTitleAr: 'التصنيفات المضافة حديثاً بعد آلات حاسبة',
          orderIndex: 32,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'خزنات',
          categorySlug: 'safes',
          sectionTitleAr: 'التصنيفات المضافة حديثاً بعد آلات حاسبة',
          orderIndex: 33,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'ألعاب ووسائل تعليمية',
          categorySlug: 'educational-toys-learning-aids',
          sectionTitleAr: 'التصنيفات المضافة حديثاً بعد آلات حاسبة',
          orderIndex: 34,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'رياضة',
          categorySlug: 'deli-sports',
          sectionTitleAr: 'التصنيفات المضافة حديثاً بعد آلات حاسبة',
          orderIndex: 35,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'مستلزمات حياة',
          categorySlug: 'deli-health-and-wellness-products',
          sectionTitleAr: 'التصنيفات المضافة حديثاً بعد آلات حاسبة',
          orderIndex: 36,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'بطاريات',
          categorySlug: 'electronics-printers-and-batteries',
          sectionTitleAr: 'التصنيفات المضافة حديثاً بعد آلات حاسبة',
          orderIndex: 37,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'تخييم',
          categorySlug: 'deli-camping',
          sectionTitleAr: 'التصنيفات المضافة حديثاً بعد آلات حاسبة',
          orderIndex: 38,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'deli',
          brandAliases: _deliBrandAliases,
          brandLabelAr: 'ديلي',
          labelAr: 'عدد',
          categorySlug: 'industrial-tool-sets',
          sectionTitleAr: 'التصنيفات المضافة حديثاً بعد آلات حاسبة',
          orderIndex: 39,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zero',
          brandAliases: _zeroBrandAliases,
          brandLabelAr: 'زيرو',
          labelAr: 'أقلام حبر جاف',
          categorySlug: 'ballpoint-pens',
          sectionTitleAr: 'الأقلام',
          orderIndex: 1,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zero',
          brandAliases: _zeroBrandAliases,
          brandLabelAr: 'زيرو',
          labelAr: 'أقلام حبر جل',
          categorySlug: 'gel-ink-pens',
          sectionTitleAr: 'الأقلام',
          orderIndex: 2,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zero',
          brandAliases: _zeroBrandAliases,
          brandLabelAr: 'زيرو',
          labelAr: 'أقلام حبر سائل',
          categorySlug: 'liquid-ink-pens',
          sectionTitleAr: 'الأقلام',
          orderIndex: 3,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zero',
          brandAliases: _zeroBrandAliases,
          brandLabelAr: 'زيرو',
          labelAr: 'أقلام تأشير',
          categorySlug: 'highlight-markers',
          sectionTitleAr: 'الأقلام',
          orderIndex: 4,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zero',
          brandAliases: _zeroBrandAliases,
          brandLabelAr: 'زيرو',
          labelAr: 'أقلام تخطيط',
          categorySlug: 'highlighters',
          sectionTitleAr: 'الأقلام',
          orderIndex: 5,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zero',
          brandAliases: _zeroBrandAliases,
          brandLabelAr: 'زيرو',
          labelAr: 'أقلام سبورة',
          categorySlug: 'whiteboard-markers',
          sectionTitleAr: 'الأقلام',
          orderIndex: 6,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zero',
          brandAliases: _zeroBrandAliases,
          brandLabelAr: 'زيرو',
          labelAr: 'أقلام رصاص',
          categorySlug: 'pencils',
          sectionTitleAr: 'الأقلام',
          orderIndex: 7,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zero',
          brandAliases: _zeroBrandAliases,
          brandLabelAr: 'زيرو',
          labelAr: 'أقلام فلوماستر',
          categorySlug: 'flomaster-coloring-pens',
          sectionTitleAr: 'الأقلام',
          orderIndex: 8,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zero',
          brandAliases: _zeroBrandAliases,
          brandLabelAr: 'زيرو',
          labelAr: 'أقلام تلوين شمع',
          categorySlug: 'crayons-pencils',
          sectionTitleAr: 'الأقلام',
          orderIndex: 9,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zero',
          brandAliases: _zeroBrandAliases,
          brandLabelAr: 'زيرو',
          labelAr: 'أقلام تلوين باستل',
          categorySlug: 'pastel-pencils',
          sectionTitleAr: 'الأقلام',
          orderIndex: 10,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zero',
          brandAliases: _zeroBrandAliases,
          brandLabelAr: 'زيرو',
          labelAr: 'أقلام دهان',
          categorySlug: 'paint-marker',
          sectionTitleAr: 'الأقلام',
          orderIndex: 11,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zero',
          brandAliases: _zeroBrandAliases,
          brandLabelAr: 'زيرو',
          labelAr: 'أقلام تصحيح',
          categorySlug: 'correction-pens',
          sectionTitleAr: 'الأقلام',
          orderIndex: 12,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zero',
          brandAliases: _zeroBrandAliases,
          brandLabelAr: 'زيرو',
          labelAr: 'غيارات أقلام',
          categorySlug: 'pen-refills',
          sectionTitleAr: 'غيارات',
          orderIndex: 13,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zero',
          brandAliases: _zeroBrandAliases,
          brandLabelAr: 'زيرو',
          labelAr: 'أقلام تلوين خشبي',
          categorySlug: 'colored-pencils',
          sectionTitleAr: 'التلوين',
          orderIndex: 14,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zero',
          brandAliases: _zeroBrandAliases,
          brandLabelAr: 'زيرو',
          labelAr: 'تلوين مائي',
          categorySlug: 'watercolor-paints',
          sectionTitleAr: 'التلوين',
          orderIndex: 15,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zero',
          brandAliases: _zeroBrandAliases,
          brandLabelAr: 'زيرو',
          labelAr: 'تلوين مائي حجري',
          categorySlug: 'watercolor-cake',
          sectionTitleAr: 'التلوين',
          orderIndex: 16,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zero',
          brandAliases: _zeroBrandAliases,
          brandLabelAr: 'زيرو',
          labelAr: 'علب هندسية وأدواتها',
          categorySlug: 'geometryboxes-drawinginstruments',
          sectionTitleAr: 'الأدوات واللوازم',
          orderIndex: 17,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zero',
          brandAliases: _zeroBrandAliases,
          brandLabelAr: 'زيرو',
          labelAr: 'محايات',
          categorySlug: 'erasers',
          sectionTitleAr: 'الأدوات واللوازم',
          orderIndex: 18,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zero',
          brandAliases: _zeroBrandAliases,
          brandLabelAr: 'زيرو',
          labelAr: 'برايات',
          categorySlug: 'sharpeners',
          sectionTitleAr: 'الأدوات واللوازم',
          orderIndex: 19,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zero',
          brandAliases: _zeroBrandAliases,
          brandLabelAr: 'زيرو',
          labelAr: 'سبورات كتابة',
          categorySlug: 'writing-and-presentation-boards',
          sectionTitleAr: 'الأدوات واللوازم',
          orderIndex: 20,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zero',
          brandAliases: _zeroBrandAliases,
          brandLabelAr: 'زيرو',
          labelAr: 'دفاتر',
          categorySlug: 'notebooks',
          sectionTitleAr: 'الأدوات واللوازم',
          orderIndex: 21,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zero',
          brandAliases: _zeroBrandAliases,
          brandLabelAr: 'زيرو',
          labelAr: 'ثقابات وخرازات',
          categorySlug: 'hole-punchers-staplers-binder-clips',
          sectionTitleAr: 'الأدوات واللوازم',
          orderIndex: 22,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zero',
          brandAliases: _zeroBrandAliases,
          brandLabelAr: 'زيرو',
          labelAr: 'بطاقات اسمية',
          categorySlug: 'name-badges',
          sectionTitleAr: 'الأدوات واللوازم',
          orderIndex: 23,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zero',
          brandAliases: _zeroBrandAliases,
          brandLabelAr: 'زيرو',
          labelAr: 'مقالم',
          categorySlug: 'pencil-cases',
          sectionTitleAr: 'الأدوات واللوازم',
          orderIndex: 24,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zero',
          brandAliases: _zeroBrandAliases,
          brandLabelAr: 'زيرو',
          labelAr: 'أربطة مطاطية',
          categorySlug: 'office-rubber-bands',
          sectionTitleAr: 'الأدوات واللوازم',
          orderIndex: 25,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zero',
          brandAliases: _zeroBrandAliases,
          brandLabelAr: 'زيرو',
          labelAr: 'تجليدات لاصقة',
          categorySlug: 'adhesive-covers',
          sectionTitleAr: 'المواد اللاصقة',
          orderIndex: 26,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zero',
          brandAliases: _zeroBrandAliases,
          brandLabelAr: 'زيرو',
          labelAr: 'مواد لاصقة',
          categorySlug: 'adhesives',
          sectionTitleAr: 'المواد اللاصقة',
          orderIndex: 27,
        ),
        // ── Zidny (زدني) ──────────────────────────────────────
        BrandScopedCategoryItemConfig(
          brandId: 'zidny',
          brandAliases: _zidnyBrandAliases,
          brandLabelAr: 'زدني',
          labelAr: 'أقلام حبر جاف',
          categorySlug: 'ballpoint-pens',
          sectionTitleAr: 'الأقلام',
          orderIndex: 1,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zidny',
          brandAliases: _zidnyBrandAliases,
          brandLabelAr: 'زدني',
          labelAr: 'أقلام رصاص',
          categorySlug: 'pencils',
          sectionTitleAr: 'الأقلام',
          orderIndex: 2,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zidny',
          brandAliases: _zidnyBrandAliases,
          brandLabelAr: 'زدني',
          labelAr: 'أقلام تأشير',
          categorySlug: 'highlighters',
          sectionTitleAr: 'الأقلام',
          orderIndex: 3,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zidny',
          brandAliases: _zidnyBrandAliases,
          brandLabelAr: 'زدني',
          labelAr: 'أقلام تصحيح',
          categorySlug: 'correction-pens',
          sectionTitleAr: 'الأقلام',
          orderIndex: 4,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zidny',
          brandAliases: _zidnyBrandAliases,
          brandLabelAr: 'زدني',
          labelAr: 'أقلام تلوين خشبي',
          categorySlug: 'colored-pencils',
          sectionTitleAr: 'الأقلام',
          orderIndex: 5,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zidny',
          brandAliases: _zidnyBrandAliases,
          brandLabelAr: 'زدني',
          labelAr: 'علب هندسية وأدواتها',
          categorySlug: 'geometryboxes-drawinginstruments',
          sectionTitleAr: 'الأدوات واللوازم',
          orderIndex: 6,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zidny',
          brandAliases: _zidnyBrandAliases,
          brandLabelAr: 'زدني',
          labelAr: 'معجون وصلصال',
          categorySlug: 'zidny-paste-and-clay',
          sectionTitleAr: 'الأدوات واللوازم',
          orderIndex: 7,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zidny',
          brandAliases: _zidnyBrandAliases,
          brandLabelAr: 'زدني',
          labelAr: 'محايات',
          categorySlug: 'erasers',
          sectionTitleAr: 'الأدوات واللوازم',
          orderIndex: 8,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zidny',
          brandAliases: _zidnyBrandAliases,
          brandLabelAr: 'زدني',
          labelAr: 'برايات',
          categorySlug: 'sharpeners',
          sectionTitleAr: 'الأدوات واللوازم',
          orderIndex: 9,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zidny',
          brandAliases: _zidnyBrandAliases,
          brandLabelAr: 'زدني',
          labelAr: 'دفاتر',
          categorySlug: 'notebooks',
          sectionTitleAr: 'الأدوات واللوازم',
          orderIndex: 10,
        ),
        BrandScopedCategoryItemConfig(
          brandId: 'zidny',
          brandAliases: _zidnyBrandAliases,
          brandLabelAr: 'زدني',
          labelAr: 'بطاقات اسمية',
          categorySlug: 'name-badges',
          sectionTitleAr: 'الأدوات واللوازم',
          orderIndex: 11,
        ),
      ];

  @override
  List<BrandScopedCategoryItemConfig> get items => _items;
}
